version: "3"
services:
  aggregate:
    image: aggragate-challenge/aggregate-service
    ports:
      - "8080:8080"
    networks:
      - aggregate-network
    depends_on:
      - review

  review:
    image: aggragate-challenge/review-service
    ports:
      - "8081:8081"
    networks:
      - aggregate-network

networks:
  aggregate-network:
